Repository 2022-Harmony/NewsCommunity-fFinal, pull requests merged in 2022-07, with the labels that each got.

#52 프로필 페이지 타이틀 수정
  profile.html
  static/js/profile_about.js
Labels: bug

#70 Feat: 프로필 페이지에서도 자신의 댓글에 사진 나오게 하기
  static/js/profile_about.js
Labels: feat

#84 프로필 페이지에서 해당 프로필의 북마크가 나오도록 수정
  static/js/profile_about.js
Labels: bug

#80 백앤드가 넘겨주는 Response 형식이 변경되어 이를 동기화 해줌
  static/js/detail.js
  static/js/listing.js
  static/js/profile_about.js
Labels: fix

#94 Feat: 댓글에서 프로필 사진 클릭시 프로필 페이지로 이동
  static/js/detail.js
Labels: feat

#93 Fix: 본인의 프로필이 아닌 프로필에서도 다른 사용자의 정보가 나오도록 수정
  static/js/profile_about.js
Labels: bug

#96 Refactor: 상세페이지 관련 코드 정리할 것들 정리
  detail.html
  static/js/basic.js
  static/js/profile_about.js
Labels: fix

#107 토큰 갱신 방식 변경
  static/js/basic.js
Labels: fix

#110 회원 가입 후 이동되는 주소 수정
  static/js/login.js
Labels: bug

#113 비로그인시 화면에 댓글 작성칸 안 보이게 수정
  detail.html
  static/js/detail.js
Labels: fix

#115 로그아웃 후 간헐적으로 자동 로그인 되던 문제 해결
  static/js/basic.js
  static/js/login.js
Labels: bug

#118 뉴스 상세페이지 댓글 페이징 기능 구현
  detail.html
  static/js/detail.js
Labels: feat

#121 토큰 갱신이 불가한 경우에도 로그아웃되지 않는 오류
  static/js/basic.js
Labels: bug

#125 Feat: 프론트 테스트 배포
  .github/workflows/main.yml
  static/js/basic.js
Labels: feat

#123 프로필 페이지 댓글 모아보기 페이징 기능
  profile.html
  static/js/profile_about.js
  static/profile.css
Labels: feat

#131 프로필url을 받아오기 위해 요청하는 url에서 api 빠진 것 추가
  static/js/detail.js
Labels: fix

#128 비로그인 사용자 뉴스 조회 불가 오류
  static/js/basic.js
Labels: bug

#134 프로필 사진에 마우스 올려놨을 때 마우스 포인터 변경
  static/detail.css
  static/js/detail.js
Labels: feat

#136 프로필 페이지에서 댓글 보여주기 위한 요청 url 수정
  static/js/profile_about.js
Labels: bug

#138 Feat: 좋아요 클릭 시 하트 상태 유지
  static/js/detail.js
  static/js/profile_about.js
Labels: feat

#140 Feat: 프로필 페이지에서 보이는 댓글의 좋아요는 클릭이 안 되게 마우스 포인터 막아버리기
  static/js/profile_about.js
  static/profile.css
Labels: enhancement

#147 클라우드 프론트 환경과 EB환경에 맞는 url 환경 구현
  detail.html
  index.html
  login.html
  profile.html
  static/js/basic.js
  static/js/detail.js
  static/js/listing.js
  static/js/login.js
  static/js/profile_about.js
  support.html
Labels: fix

#145 토큰 갱신 관련 오류 해결
  static/js/basic.js
Labels: bug

#152 잔재 삭제 수정 & 좋아요 확인 기능 수정
  detail.html
  index.html
  profile.html
  static/js/detail.js
  static/js/login.js
  static/js/profile_about.js
  support.html
Labels: bug, fix

#165 프론트앤드 코드 배포를 수행시키는 트리거를 develop에서 main브랜치로 변경
  .github/workflows/main.yml
Labels: fix

#167 상세페이지 댓글 페이징 개선 및 정렬 기능
  detail.html
  static/js/detail.js
Labels: bug, fix

#169 프로필 페이지 댓글 페이징 번호 개선
  static/js/profile_about.js
Labels: fix

#174 [Deploy] 2022-07-26 댓글 페이지 기능 개선 패치
  .github/ISSUE_TEMPLATE/harmony-issue-template.md
  .github/pull_request_template.md
  .github/workflows/main.yml
  detail.html
  index.html
  login.html
  profile.html
  static/base.css
  static/detail.css
  static/js/basic.js
  static/js/detail.js
  static/js/listing.js
  static/js/login.js
  static/js/profile_about.js
  static/js/support.js
  static/js/ui.js
  static/profile.css
  static/support.css
  support.html
Labels: feat

#171 기존 정렬기능 구현했던 코드 삭제
  static/js/detail.js
Labels: refactor

#175 댓글 요청 url 배포 서버 주소로 수정
  static/js/detail.js
Labels: refactor

#177 페이징 locator 와 정렬 부분 디자인 개선
  detail.html
  profile.html
  static/detail.css
  static/js/detail.js
  static/js/profile_about.js
  static/profile.css
Labels: design

#179 회원 가입 Content-Type Json으로 변경
  static/js/login.js
Labels: refactor

#182 좋아요 관련 피드백 보완
  static/js/detail.js
Labels: fix

#184 [Deploy] 2022-07-27 좋아요 기능 개선 패치
  detail.html
  profile.html
  static/detail.css
  static/js/detail.js
  static/js/login.js
  static/js/profile_about.js
  static/profile.css
Labels: deploy
